### PR TITLE
Update to new flutter engine;

### PR DESCRIPTION
**Pull request by mehdok**

### CODE REVIEW

**Comment by mehdok** [comment]
#220 
#215 
#203 
#197 
#194

**Comment by ramism16** [comment]
Have you managed to fix the known bug?

**Comment by mehdok** [comment]
@ramism16 

This `PR` might be the answer, but I have to fix the iOS part too before merging it.
It would be nice if you could pull this and test it on Android.

**Comment by SardorbekR** [comment]
When are you going to publish the new update?

**Comment by DebkanchanSamadder** [comment]
Highly anticipated update. Looking out for a release soon.

**Comment by mehdok** [comment]
Hi guys
Thank you for your interest, this PR still need some work and I was so busy to work on it. 
But this weekend I will publish it ;)

**Comment by mehdok** [comment]
@ramism16 @SardorbekR @DebkanchanSamadder 

Hi guys, I have published this version as a beta version because there are too many changes in this `PR` and it needs a lot of testing. Please test the new version and let me know if somethings not working;

**Comment by DebkanchanSamadder** [comment]
Sure! Will implement in a few days and let you know

**Comment by DebkanchanSamadder** [comment]
Sorry @mehdok due to situation I couldn't implement and test it out. I see you've published an update. Thanks

**Comment by DebkanchanSamadder** [comment]
> Could you explain what the reason was to remove the init and dispose callbacks? For me, they were useful to do some setup and also teardown work when location tracking was starting and ending.

+1 I used them very seriously. I'm having hard time implementing them with this setup

**Comment by gpibarra** [comment]
> Could you explain what the reason was to remove the init and dispose callbacks? For me, they were useful to do some setup and also teardown work when location tracking was starting and ending.

@wwwdata  @DebkanchanSamadder 

https://github.com/rekab-app/background_locator/issues/227

**Pull request merged**
