### PR TITLE
Use region monitoring for background location

### PR DESCRIPTION
**Pull request by martofeld**
Possible fix for #54.

By using region monitoring we lower the distance that needs to be covered before the new location is notified (vs significantChangesMonitoring). I've tested it in the emulator since I don't have an iOS device with me right now.

### CODE REVIEW

**Comment by martofeld** [comment]
@mehdok Is there any chance you could take a look at this PR?

**Comment by mehdok** [comment]
@martofeld Sorry I wasn't around lately, I will look it in a few days.

**Comment by mehdok** [comment]
@martofeld  First of all I have to say that your idea is really good.
I have tested your code very carefully. I even created a separate iOS project with your idea, and it is really working. 

When app is terminated (removed from recent) a sequence of methods is getting called. `didFinishLaunchingWithOptions` --> `didExitRegion` --> `didUpdateLocations`.

_BUT_ when I start the app again I can not see any any saved location. maybe we need to do something like [this](https://github.com/rekab-app/background_locator/wiki/Use-other-plugins-in-callback) for iOS.

I'm looking into it, but I will appreciate any idea.

**Comment by ovaldi** [comment]
Hi @martofeld I also meet this issue, did you fix it?

> _BUT_ when I start the app again I can not see any saved location. maybe we need to do something like [this](https://github.com/rekab-app/background_locator/wiki/Use-other-plugins-in-callback) for iOS.
>

**Comment by martofeld** [comment]
@ovaldi Unfortunately the project I was working on dropped, so I didn't get a chance to test it again. But my understanding is that @mehdok fixed it

**Comment by mehdok** [comment]
@martofeld  @ovaldi The code is merged and iOS part is working fine right now;

**Pull request merged**
