### PR TITLE
Added support for the new android plugin api

### PR DESCRIPTION
**Pull request by dacianf**
@mehdok Please take a look over this pr and check if I need something else to do.

Fixes brought by porting lib to the new android plugin:

- No need of manual registration for 3rd party plugins in Android
- BackgroundLocatorPlugin methods can be accessed in callback (for example notification can be updated, or plugin can be stoped from callback)

Maybe this also fix [issue 67](https://github.com/rekab-app/background_locator/issues/67)

### CODE REVIEW

**Comment by mehdok** [comment]
Thank you for spending time on fixing the issue.

I can see that you have done lots of fundamental changes, eg. Using `FlutterEngine` instead of `FlutterNativeView` or have used `DartExecutor.DartCallback`, it would be a lot easier to review if you provide some comments for this changes;

**Comment by idootop** [comment]
> Thank you for spending time on fixing the issue.
> 
> I can see that you have done lots of fundamental changes, eg. Using `FlutterEngine` instead of `FlutterNativeView` or have used `DartExecutor.DartCallback`, it would be a lot easier to review if you provide some comments for this changes;

Just updated for Flutter Android Embedding v2, then No need of manual registration for 3rd party plugins in Android.
I'm sure this PR is working and very useful, thanks @dacianf.
This package is so awesome, thanks for your efforts. ❤️

**Comment by yu3fms** [comment]
Hi,

I have run example app from this PR, at first flutter gave following error:

java.lang.RuntimeException: Unable to instantiate application rekab.app.background_locator_example.Application: java.lang.ClassNotFoundException: Didn't find class "rekab.app.background_locator_example.Application" on path: DexPathList[[zip file "/data/app/rekab.app.background_locator_example-LhXwldicuJXozGemrUCDKQ==/base.apk"],nativeLibraryDirectories=[/data/app/rekab.app.background_locator_example-LhXwldicuJXozGemrUCDKQ==/lib/arm64, /data/app/rekab.app.background_locator_example-LhXwldicuJXozGemrUCDKQ==/base.apk!/lib/arm64-v8a, /system/lib64, /hw_product/lib64, /system/product/lib64, /prets/lib64]]
E/AndroidRuntime(23406): 	at android.app.LoadedApk.makeApplication(LoadedApk.java:1304)
E/AndroidRuntime(23406): 	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:7320)
E/AndroidRuntime(23406): 	at android.app.ActivityThread.access$2400(ActivityThread.java:308)
E/AndroidRuntime(23406): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2295)
E/AndroidRuntime(23406): 	at android.os.Handler.dispatchMessage(Handler.java:110)
E/AndroidRuntime(23406): 	at android.os.Looper.loop(Looper.java:219)
E/AndroidRuntime(23406): 	at android.app.ActivityThread.main(ActivityThread.java:8347)
E/AndroidRuntime(23406): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(23406): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:513)
E/AndroidRuntime(23406): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1055)
E/AndroidRuntime(23406): Caused by: java.lang.ClassNotFoundException: Didn't find class "rekab.app.background_locator_example.Application" on path: DexPathList[[zip file "/data/app/rekab.app.background_locator_example-LhXwldicuJXozGemrUCDKQ==/base.apk"],nativeLibraryDirectories=[/data/app/rekab.app.background_locator_example-LhXwldicuJXozGemrUCDKQ==/lib/arm64, /data/app/rekab.app.background_locator_example-LhXwldicuJXozGemrUCDKQ==/base.apk!/lib/arm64-v8a, /system/lib64, /hw_product/lib64, /system/product/lib64, /prets/lib64]]
E/AndroidRuntime(23406): 	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:209)
E/AndroidRuntime(23406): 	at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
E/AndroidRuntime(23406): 	at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
E/AndroidRuntime(23406): 	at android.app.AppComponentFactory.instantiateApplication(AppComponentFactory.java:76)
E/AndroidRuntime(23406): 	at androidx.core.app.CoreComponentFactory.instantiateApplication(CoreComponentFactory.java:47)
E/AndroidRuntime(23406): 	at android.app.Instrumentation.newApplication(Instrumentation.java:1167)
E/AndroidRuntime(23406): 	at android.app.LoadedApk.makeApplication(LoadedApk.java:1296)
E/AndroidRuntime(23406): 	... 9 more

But I have "fixed" this by creating "MainActivity.kt" file at the kotlin subdirs, which is removed in this fork.

When I got it running on a device with Android10 everything works ok except the updating notification text when the app is terminated. If I understand correctly, this PR should enable us to do just that?

Could You please tell me if I have missed something and how (if it is possible) to update notification text from callback when app is terminated?

Flutter (Channel stable, 1.22.4, on macOS 11.1 20C69 darwin-arm, locale en-RS)
Android toolchain - develop for Android devices (Android SDK version 30.0.3)

**Comment by mehdok** [comment]
> When I got it running on a device with Android10 everything works ok except the updating notification text when the app is terminated. If I understand correctly, this PR should enable us to do just that?

This _PR_ is supposed to make the integration process easier without breaking anything.

**Comment by yu3fms** [comment]
OK, thank You.
Managed to update notification with a bit of a trick. Using "flutter_local_notifications" plugin in callback in "location_service_repository.dart" and setting the same NOTIFICATION_ID and CHANNEL_ID when displaying a notification with "flutter_local_notifications" plugin.

**Comment by mehdok** [comment]
@dacianf 

This `PR` was open for so long and there was too many conflicts, so I tried to implement it in new branch #222 ;

**Pull request closed without merging**
