### PR TITLE
Making Readme more fun

### PR DESCRIPTION
**Pull request by RomanJos**
Hi with the change of @marceloneppel I think its time to really make this plugins more accessible so I modified the readme by adding emoji and a gif and I think it look cool, however there are some things that I don't know so if someone could review it that would be super cool

### CODE REVIEW

**Comment by mehdok** [comment]
Thank you for this. Plugin looks alive now.

**Comment by RomanJos** [comment]
Ohh lol I didn't thought you will merge it this fast lmao in the permission I detail most of them except 
INTERNET, ACCESS_BACKGROUND_LOCATION because I don't understand why the plugins need it and ACCESS_FINE_LOCATION because I suppose if you make a LOW request you can access the location with ACCESS_COARSE_LOCATION
On the IOS part I didn't modified anything because I don't know at all how IOS work lol and its really small compared to Android so if someone know IOS then please edit that part
I just see that I forgot to put the link of the example
In How to use it -> step 3 I put (this should be optional) talking about the android callback because if we don't specify this callback we get an error, I put this to remember to ask you if you could make it optional so : can you make it optional ? 
And as you probably saw I changed the instruction of @marceloneppel in the Android part because I couldn't make it work so I guess its okay but Marcel if you could check it out that would be perfect

**Comment by mehdok** [comment]
So indeed it needed a review :)

`ACCESS_FINE_LOCATION`: You have to include this to get precise location. As you said if you make a `LOW` request you don't need this. But there is no harm for adding this all the time and let the user not to be confused.

android notification callback: Yes, it should be optional, I will fix it.

iOS: There is no need to change anything in iOS. But it is good if someone else test it and see if it works all the way.

**Comment by gpibarra** [comment]
In the Readme.md, function "dispose", line "BackgroundLocator.unRegisterLocationUpdate();". its work? its stop service and not will running in background. I am right?

**Comment by RomanJos** [comment]
> 
> 
> In the Readme.md, function "dispose", line "BackgroundLocator.unRegisterLocationUpdate();". its work? its stop service and not will running in background. I am right?

Absolutely, it will stop the service and the notification will disapear, the only things that I don't know is why it need a Isolate but you need to stop it also

**Comment by mehdok** [comment]
@gpibarra I'm not exactly sure what are you talking about. But if you call `BackgroundLocator.unRegisterLocationUpdate();` The plugin will stop immediately, The place of calling doesn't matter. if you call it in `dispose` function you are saying that you don't want any update when app is not if foreground. 

@RomanJos The `Isolate` is necessary for UI update, and when there is no UI it's better to stop it.

**Comment by RomanJos** [comment]
> 
> 
>  if you call it in `dispose` function you are saying that you don't want any update when app is not if foreground.

I put it in dispose and it work well in the background

> The `Isolate ` is necessary for UI update, and when there is no UI it's better to stop it.

So the Isolate is only to communicate LocationDto to the listen callback ? Do you think we can use a Stream for that instead ?

**Pull request merged**
